# This config file for Travis CI utilizes https://github.com/ros-planning/moveit_ci/ package.
sudo: required
dist: xenial
services:
  - docker
language: generic
compiler:
  - gcc
notifications:
  email:
    recipients:
      - 130s@2000.jukuin.keio.ac.jp
      - jrgnichodevel@gmail.com
env:
  matrix:
    - ROS_DISTRO=kinetic ROS_REPO=ros              
    - ROS_DISTRO=kinetic ROS_REPO=ros-shadow-fixed 
    - ROS_DISTRO=kinetic TEST=clang-format         
before_script:
  - git clone -q https://github.com/ros-planning/moveit_ci.git .moveit_ci
script:
  - source .moveit_ci/travis.sh
